In [1]:
import datetime as dt
import pandas as pd
import numpy as np
import csv
import sys

In [2]:
#carregar arquivo
base_filtrada = pd.read_csv('dataset-filtrado.csv',sep=',',encoding='iso-8859-1', dtype='object', usecols=['sIP-forward', 'dIP-forward', 'packets-forward',
       "bytes-forward'", 'sTime-forward', 'dur+msec-forward', 'ap'])

In [3]:
#passando pra datetime 
base_filtrada['sTime-forward-datetime'] = pd.to_datetime(base_filtrada['sTime-forward'], origin = 'unix', unit = 's')
#base_filtrada['sTime-forward-datetime']

In [4]:
base_filtrada['sTime-forward-datetime-time'] = base_filtrada['sTime-forward-datetime'].dt.strftime("%H")
#base_filtrada['sTime-forward-datetime-time']

In [5]:
base_filtrada['sTime-forward-datetime-day'] = base_filtrada['sTime-forward-datetime'].dt.strftime("%d")
#base_filtrada['sTime-forward-datetime-day']

In [7]:
base_filtrada_dia_24_11h = base_filtrada[(base_filtrada['sTime-forward-datetime-day']== '24') & (base_filtrada['sTime-forward-datetime-time']== '11')]
#base_filtrada_dia_24_11h

In [8]:
tmin = base_filtrada_dia_24_11h['sTime-forward'].min()

In [10]:
base_filtrada_dia_24_11h['sTime-forward'].astype(float)
base_filtrada_dia_24_11h['sTime-forward']

35124072    1524567606.71
35124073    1524567617.59
35124074    1524567607.79
35124075    1524567623.96
35124076    1524567623.96
                ...
35129831    1524571114.03
35129841    1524570791.99
35129851    1524571195.63
35129852    1524571195.63
35129853    1524571195.63
Name: sTime-forward, Length: 5738, dtype: object

In [12]:
#achando o tnovo partindo de 0s
tmin = float(tmin)
base_filtrada_dia_24_11h['sTime-foward-0start'] = base_filtrada_dia_24_11h['sTime-forward'].astype(float).map(lambda x: x - tmin)
#base_filtrada_dia_24_11h['sTime-foward-0start']

C:\Users\CarolinaBaptistadeli\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
base_filtrada_dia_24_11h.head()

,sIP-forward,dIP-forward,packets-forward,bytes-forward',sTime-forward,dur+msec-forward,ap,sTime-forward-datetime,sTime-forward-datetime-time,sTime-forward-datetime-day,sTime-foward-0start
35124072,10.1.106.231,172.217.29.106,2,104,1524567606.71,0.0,ap0222,2018-04-24 11:00:06.710000038,11,24,0.00
35124073,10.1.106.231,188.65.124.58,6,4533,1524567617.59,0.0,ap0222,2018-04-24 11:00:17.589999914,11,24,10.88
35124074,10.1.106.228,169.47.5.238,10,622,1524567607.79,13.13,ap0604,2018-04-24 11:00:07.789999962,11,24,1.08
35124075,10.1.106.226,8.8.8.8,2,150,1524567623.96,0.0,ap0055,2018-04-24 11:00:23.960000038,11,24,17.25
35124076,10.1.106.226,8.8.8.8,2,150,1524567623.96,0.0,ap0055,2018-04-24 11:00:23.960000038,11,24,17.25

In [17]:
base_filtrada_dia_24_11h.sort_values(['sTime-foward-0start'])

,sIP-forward,dIP-forward,packets-forward,bytes-forward',sTime-forward,dur+msec-forward,ap,sTime-forward-datetime,sTime-forward-datetime-time,sTime-forward-datetime-day,sTime-foward-0start
35124072,10.1.106.231,172.217.29.106,2,104,1524567606.71,0.0,ap0222,2018-04-24 11:00:06.710000038,11,24,0.00
35124074,10.1.106.228,169.47.5.238,10,622,1524567607.79,13.13,ap0604,2018-04-24 11:00:07.789999962,11,24,1.08
35124073,10.1.106.231,188.65.124.58,6,4533,1524567617.59,0.0,ap0222,2018-04-24 11:00:17.589999914,11,24,10.88
35124075,10.1.106.226,8.8.8.8,2,150,1524567623.96,0.0,ap0055,2018-04-24 11:00:23.960000038,11,24,17.25
35124076,10.1.106.226,8.8.8.8,2,150,1524567623.96,0.0,ap0055,2018-04-24 11:00:23.960000038,11,24,17.25
...,...,...,...,...,...,...,...,...,...,...,...
35129851,10.1.106.231,216.58.222.98,8,416,1524571195.63,48.82,ap0222,2018-04-24 11:59:55.630000114,11,24,3588.92
35129853,10.1.106.231,216.58.222.98,8,416,1524571195.63,48.82,ap0222,2018-04-24 11:59:55.630000114,11,24,3588.92
35129852,10.1.106.231,216.58.222.98,8,416,1524571195.63,48.82,ap0222,2018-04-24 11:59:55.630000114,11,24,3588.92
35129797,10.1.106.231,163.172.113.28,2,104,1524571196.22,0.0,ap0222,2018-04-24 11:59:56.220000029,11,24,3589.51
35129798,10.1.106.231,31.216.148.10,2,104,1524571198.16,0.0,ap0222,2018-04-24 11:59:58.160000086,11,24,3591.45

In [18]:
base_dia_24_11h_foward = base_filtrada_dia_24_11h.replace({'dur+msec-forward': {'0': '1', '0.0': '1.0'}})

In [20]:
base_dia_24_11h_foward = base_dia_24_11h_foward.sort_values(['sTime-foward-0start'])

In [21]:
base_dia_24_11h_foward.head()

,sIP-forward,dIP-forward,packets-forward,bytes-forward',sTime-forward,dur+msec-forward,ap,sTime-forward-datetime,sTime-forward-datetime-time,sTime-forward-datetime-day,sTime-foward-0start
35124072,10.1.106.231,172.217.29.106,2,104,1524567606.71,1.0,ap0222,2018-04-24 11:00:06.710000038,11,24,0.00
35124074,10.1.106.228,169.47.5.238,10,622,1524567607.79,13.13,ap0604,2018-04-24 11:00:07.789999962,11,24,1.08
35124073,10.1.106.231,188.65.124.58,6,4533,1524567617.59,1.0,ap0222,2018-04-24 11:00:17.589999914,11,24,10.88
35124075,10.1.106.226,8.8.8.8,2,150,1524567623.96,1.0,ap0055,2018-04-24 11:00:23.960000038,11,24,17.25
35124076,10.1.106.226,8.8.8.8,2,150,1524567623.96,1.0,ap0055,2018-04-24 11:00:23.960000038,11,24,17.25

In [22]:
#extrair base com modificações
base_dia_24_11h_foward[['sTime-foward-0start', 'sIP-forward', 'dIP-forward', 'ap', 'dur+msec-forward', 'packets-forward']].to_csv('base_dia_24_11h_foward.txt', encoding='utf-8', sep=',', index=False, header=False)